### ISSUE TITLE
关于Android-release包出现的aar缺失问题

### ISSUE THREAD

**Issue by zplblue** [zileyuan/umeng_analytics_push#10]
我引入了这个插件。在debug模式下正常，
但是当我执行 flutter build apk.打出releaes包的时候，打开应用提示：sdk初始化失败，请检查是否集成umeng-crash-x.x.X.aar库，和 “common sdk 版本不匹配，请确认”的错误。不知道你在测试的时候出现了这个问题没有

**Comment by zileyuan** [comment]
你应该安装过老版本的umeng sdk， 清除以后再试

**Comment by zplblue** [comment]
> 你应该安装过老版本的umeng sdk， 清除以后再试
我也想到了这个情况，还有包冲突问题；我新建了一个Flutter项目，只引入了这个plugin.debug正常；release同样报错。我计划在插件中手动引入不适用maven的方式试一下。不知道可行不可行。

**Comment by zplblue** [comment]
@zileyuan 后续又试了半天。发现不是umeng sdk的问题。是flutter 在打release包的时候如果你不设置混淆的话。会自动混淆。将混淆设置成false后，release包不报错了。可以关闭这个issue了。
