### ISSUE TITLE
安卓打apk包安装会提示，SDK初始化失败，请检查是否安装umeng-crash-armeabi-vX.X.X.aar文件

### ISSUE THREAD

**Issue by wh8817221** [zileyuan/umeng_analytics_push#16]
1、正式版基础组件库 9.3.3 中移除了umeng-crash-armeabi-vX.X.X.aar文件，如果需要错误捕获能力，请集成应用性能监控SDK。集成文档为：https://developer.umeng.com/docs/193624/detail/194590

**Comment by wh8817221** [comment]
作者什么时候优化一下

**Comment by zileyuan** [comment]
1.2.05
