### ISSUE TITLE
Toast提示注册有误

### ISSUE THREAD

**Issue by zhanghsgithub** [zileyuan/umeng_analytics_push#22]
E/UMLog   (23183): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/UMLog   (23183): │     com.umeng.message.proguard.h
E/UMLog   (23183): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/UMLog   (23183): ┌───────────────────问题─────────────────────────────────────────────────────────────────────────────
E/UMLog   (23183): │     Toast提示注册有误
E/UMLog   (23183): ├───────────────────解决方案─────────────────────────────────────────────────────────────────────────────
E/UMLog   (23183): │     Toast提示mPushAgent.register should be called in both main process and channel process。详见问题链接 https://developer.umeng.com/docs/66632/detail/67140?um_channel=sdk
E/UMLog   (23183): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by hxljy** [comment]
https://www.sysapi.com/article/220359.html

**Comment by zileyuan** [comment]
PushSDK初始化时，需在Application类的onCreate中调用mPushAgent.register方法来进行注册。请勿在调用register方法时做进程判断处理，主进程和channel进程（推送进程）均需要调用register才能保证长连接的正确建立。为了防止开发者初始化错误，我们增加了动态代码检查，并弹出Toast提示。所以看到此提示时，首先要检查你的代码中Application的onCreate方法里是否做了只在主进程中初始化PushSDK的判断，如果是，那么就请修改你的代码哦，将判断是否处于主进程的if语句删除就好了。需要了解的知识点： 每个进程在创建后，都会调用Application的onCreate方法。


你按说明文档进行配置

**Comment by gingerJY** [comment]
> E/UMLog (23183): ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────── E/UMLog (23183): │ com.umeng.message.proguard.h E/UMLog (23183): └──────────────────────────────────────────────────────────────────────────────────────────────────────────────── E/UMLog (23183): ┌───────────────────问题───────────────────────────────────────────────────────────────────────────── E/UMLog (23183): │ Toast提示注册有误 E/UMLog (23183): ├───────────────────解决方案───────────────────────────────────────────────────────────────────────────── E/UMLog (23183): │ Toast提示mPushAgent.register should be called in both main process and channel process。详见问题链接 https://developer.umeng.com/docs/66632/detail/67140?um_channel=sdk E/UMLog (23183): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Hey, bro, have you solved your problem yet?I have the same problem.
