### ISSUE TITLE
Unable to resolve dependency for ':umeng_analytics_push@debug/compileClasspath': Could not resolve com.umeng.umsdk:vivo-umengaccs:1.2.1.

### ISSUE THREAD

**Issue by wh8817221** [zileyuan/umeng_analytics_push#23]
我升级flutter2.0.3后然后umeng_analytics_push也更新到了2.0.1运行会提示这个错误：

Unable to resolve dependency for ':umeng_analytics_push@debug/compileClasspath': Could not resolve com.umeng.umsdk:vivo-umengaccs:1.2.1.
Show Details
Affected Modules: umeng_analytics_push

Unable to resolve dependency for ':umeng_analytics_push@debugAndroidTest/compileClasspath': Could not resolve com.umeng.umsdk:vivo-umengaccs:1.2.1.
Show Details
Affected Modules: umeng_analytics_push

Unable to resolve dependency for ':umeng_analytics_push@debugUnitTest/compileClasspath': Could not resolve com.umeng.umsdk:vivo-umengaccs:1.2.1.
Show Details
Affected Modules: umeng_analytics_push

作者遇到这个问题了吗？或者有解决方法吗？

**Comment by wh8817221** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/17784687/114005674-58f48880-9892-11eb-9c0c-af96d8af45e0.png">
你这个版本和官方的不一致啊

**Comment by creky** [comment]
降级到2.0.0版本即可，2.0.1版本在引用vivo那个依赖时把1.1.2错写成1.2.1了，官方最新的是1.1.2

**Comment by wh8817221** [comment]
> 降级到2.0.0版本即可，2.0.1版本在引用vivo那个依赖时把1.1.2错写成1.2.1了，官方最新的是1.1.2

好的，谢谢！

**Comment by zileyuan** [comment]
已经更新版本 2.0.2 和  1.2.6 都修复了
