### ISSUE TITLE
README应该更新了

### ISSUE THREAD

**Issue by renntbenrennt** [zileyuan/umeng_analytics_push#27]
![image](https://user-images.githubusercontent.com/13610283/118767364-3baed300-b8b0-11eb-9711-632c369126bd.png)

如图，文档里面说到，如果不需要开启推送的话，设置这个 `uemng_push_id` 为空，但是却没有这样的一个参数的处理。

然后这个类里面的方法调用也没有最后的参数去开启自定义推送那些了
`UmengAnalyticsPushFlutterAndroid.androidInit`

最后有个问题，按照目前的提供的方法，是不是没办法关闭这个友盟推送呢？

谢谢

**Comment by zileyuan** [comment]
已经更新了
