### ISSUE TITLE
ios编译错误

### ISSUE THREAD

**Issue by gaoyong06** [zileyuan/umeng_analytics_push#3]
在xcode中build时，出现下面的错误

2020-06-08 20:04:11.592615+0800 Runner[865:196865] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
2020-06-08 20:04:11 UMengAnalytics<6.1.0>(Debug):[UMANError:62]UMAnalytics error:session_id=6D5E2A6F0926FDA973E0EA181058CE35, context=+[UmengAnalyticsPushPlugin onListenWithArguments:eventSink:]: unrecognized selector sent to class 0x102a096d8
(null)
((
	0   CoreFoundation                      0x0000000194768178 9624AAFD-5437-3772-A507-0F357875808D + 1253752
	1   libobjc.A.dylib                     0x000000019447cc1c objc_exception_throw + 60
	2   CoreFoundation                      0x000000019466b440 9624AAFD-5437-3772-A507-0F357875808D + 218176
	3   CoreFoundation                      0x000000019476c85c 9624AAFD-5437-3772-A507-0F357875808D + 1271900
	4   CoreFoundation                      0x000000019476eb60 _CF_forwarding_prep_0 + 96
	5   Flutter                             0x000000010387b7e0 ___ZL39SetStreamHandlerMessageHandlerOnChannelPU31objcproto20FlutterStreamHandler8NSObjectP8NSStringPU33objcproto22FlutterBinaryMessengerS_PU29objcproto18FlutterMethodCodecS__block_invoke + 344
	6   Flutter                             0x000000010381207c _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 504
	7   Flutter                             0x000000010386b88c _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_32NS_9allocatorIS8_EEFvvEEclEv + 80
	8   Flutter                             0x0000000103822928 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 1616
	9   Flutter                             0x0000000103824c8c _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
	10  CoreFoundation                      0x00000001946e3efc 9624AAFD-5437-3772-A507-0F357875808D + 712444
	11  CoreFoundation                      0x00000001946e3c14 9624AAFD-5437-3772-A507-0F357875808D + 711700
	12  CoreFoundation                      0x00000001946e3288 9624AAFD-5437-3772-A507-0F357875808D + 709256
	13  CoreFoundation                      0x00000001946ddfe0 9624AAFD-5437-3772-A507-0F357875808D + 688096
	14  CoreFoundation                      0x00000001946dd660 CFRunLoopRunSpecific + 480
	15  GraphicsServices                    0x000000019eaee604 GSEventRunModal + 164
	16  UIKitCore                           0x00000001988b215c UIApplicationMain + 1944
	17  Runner                              0x00000001022ad968 main + 80
	18  libdyld.dylib                       0x00000001945591ec 95B366E7-F5BD-3308-9416-24B35999029B + 4588
)

dSYM UUID: A88A85E4-B68A-3BE8-B9E5-15082B3C4D07
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: Runner
Base Address: 0x00000001022a4000

2020-06-08 20:04:11 UMengAnalytics<6.1.0>(Debug):[UMANTerminate:126]UMAnalytics session:session_id=6D5E2A6F0926FDA973E0EA181058CE35, duration=2241.000000
libc++abi.dylib: terminate_handler unexpectedly threw an exception
(lldb)

**Comment by gaoyong06** [comment]
**[UmengAnalyticsPushPlugin onListenWithArguments:eventSink:]: unrecognized selector sent to class 0x102a096d8**

我估计是这里出错了，挺严重的bug, 在ios上没法编译，又得全部注释掉，辛苦&麻烦作者，优先优先优先先把这个处理下哈😃

**Comment by zileyuan** [comment]
我用xcode 没有出现编译错误，你是什么版本和环境？

**Comment by gaoyong06** [comment]
> 我用xcode 没有出现编译错误，你是什么版本和环境？

xcode version: 11.5
ios version: 12.4.6 (iphone 5s)
ios version: 13.4.1 (iPhone Xs Max)

我在两个iphone手机上编译，都有这个问题

**Comment by gaoyong06** [comment]
> 我用xcode 没有出现编译错误，你是什么版本和环境？

我把你的项目down下来，跑了一下example， 这个example里面是空的，没有集成umeng_analytics_push 相关的业务

文档里面用的是swift， 在AppDelegate.swift要增加一些umeng相关的代码，但是example里面 是object-c AppDelegate.m里面也没有增加和umeng相关的代码，你这是怎么测试验证的😂

**Comment by zileyuan** [comment]
> > 我用xcode 没有出现编译错误，你是什么版本和环境？
> 
> 我把你的项目down下来，跑了一下example， 这个example里面是空的，没有集成umeng_analytics_push 相关的业务
> 
> 文档里面用的是swift， 在AppDelegate.swift要增加一些umeng相关的代码，但是example里面 是object-c AppDelegate.m里面也没有增加和umeng相关的代码，你这是怎么测试验证的😂

我是在我自己的项目里面使用的，example里面没做东西

**Comment by bastYYJ** [comment]
> > 我用xcode 没有出现编译错误，你是什么版本和环境？
> 
> 我把你的项目down下来，跑了一下example， 这个example里面是空的，没有集成umeng_analytics_push 相关的业务
> 
> 文档里面用的是swift， 在AppDelegate.swift要增加一些umeng相关的代码，但是example里面 是object-c AppDelegate.m里面也没有增加和umeng相关的代码，你这是怎么测试验证的😂

我用也不好使，找到解决方案了吗

**Comment by zileyuan** [comment]
新版本 我固定了一下  umeng的 版本， umeng6.1.0 有问题 你可以试试

**Comment by zileyuan** [comment]
CLOSE
