### ISSUE TITLE
请问如何解决工信部的隐私合规的问题？

### ISSUE THREAD

**Issue by zhanghsgithub** [zileyuan/umeng_analytics_push#30]
为保证您的App在集成【友盟+】统计SDK之后，能够满足工信部相关合规要求，您应确保App首次冷启动时，在用户阅读您的《隐私政策》并取得用户授权之后，才调用正式初始化函数初始化统计SDK，此时SDK才会真正采集设备信息并上报数据。反之，如果用户不同意《隐私政策》授权，则不能调用初始化函数。

**Comment by BadReese** [comment]
+1

**Comment by zileyuan** [comment]
2.1.0已经支持了《隐私合规》
