### ISSUE TITLE
sdk初始化失败， 请检查是否集成umeng-asms-1.2x.aar，  是否是工信部的隐私合规的问题？

### ISSUE THREAD

**Issue by 164250072** [zileyuan/umeng_analytics_push#31]
打成release包安装后， 提示sdk初始化失败， 请检查是否集成umeng-asms-1.2x.aar，   是否是工信部的隐私合规的问题？

**Comment by zileyuan** [comment]
2.1.0已经支持了《隐私合规》

**Comment by kiss-keray** [comment]
我也是这个错？没写过安卓  隐私合规是啥意思？

**Comment by kiss-keray** [comment]
> 打成release包安装后， 提示sdk初始化失败， 请检查是否集成umeng-asms-1.2x.aar， 是否是工信部的隐私合规的问题？

老哥 有没有解决这个问题啊？

**Comment by zileyuan** [comment]
看文档说明，启动时候先调用 preinit

**Comment by kiss-keray** [comment]
> 看文档说明，启动时候先调用 preinit

用法都是对的。是flutter版本问题，用的最新的2.2.4，安卓默认混淆了，关闭友盟的混淆就好了。

**Comment by zjypp** [comment]
> > 看文档说明，启动时候先调用 preinit
> 
> 用法都是对的。是flutter版本问题，用的最新的2.2.4，安卓默认混淆了，关闭友盟的混淆就好了。

怎么关闭友盟的混淆啊，没有api吧

**Comment by kiss-keray** [comment]
> 修改这个文件android/app/proguard-rules.pro

# ====== 极光推送混淆 start ======
-dontoptimize
-dontpreverify
-dontwarn cn.jpush.**
-keep class cn.jpush.** { *; }
-keep class * extends cn.jpush.android.helpers.JPushMessageReceiver { *; }

-dontwarn cn.jiguang.**
-keep class cn.jiguang.** { *; }

-dontwarn com.google.**
-keep class com.google.gson.** {*;}
-keep class com.google.protobuf.** {*;}

# ====== 极光推送混淆 end ======
