### ISSUE TITLE
新版本2.1.0集成后， app崩溃

### ISSUE THREAD

**Issue by 164250072** [zileyuan/umeng_analytics_push#32]
新版本2.1.0集成后， app不知为何崩溃，没有任何日志信息

**Comment by 164250072** [comment]
百度听闻原因是： 小米系统在覆盖安装或升级新版本应用的时候如果老版本和新版本存在相同库文件并不会重新加载进系统导致新版本安装之后用的还是老版本加载的库文件，然而新版本由于新增了混淆而与老版本的缓存文件之间没有必要的关联，从而导致找不到方法名而报错。

**Comment by zileyuan** [comment]
你用android studio 应该会有log相关的

**Comment by zileyuan** [comment]
也可以试试 最新的版本  2.1.2
