### ISSUE TITLE
type '(String) => Null' is not a subtype of type '((dynamic) => void)?'

### ISSUE THREAD

**Issue by ultrapower8** [zileyuan/umeng_analytics_push#4]
UmengAnalyticsPush.addPushCustomMessageCallback((custom) {
      print("custom:{$custom}");
});
运行到此处报错
I/NAccs.MsgDistribute(10345):  handBroadCastMsg command:103

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building AppWrapper(state: _AppWrapperState#c48d2):
**type '(String) => Null' is not a subtype of type '((dynamic) => void)?'**

**Comment by zileyuan** [comment]
你这个出现空指针，你的代码要贴全

**Comment by zileyuan** [comment]
CLOSE

**Comment by zileyuan** [comment]
CLOSE
