### ISSUE TITLE
androidPreInit和androidInit分别在哪里用？

### ISSUE THREAD

**Issue by gingerJY** [zileyuan/umeng_analytics_push#44]
在您的文档中，一开始MyFlutterApplication如下图，用了androidPreInit
![image](https://user-images.githubusercontent.com/23522394/152740645-fefd7b06-9a23-4588-95de-01f6c8e4e8d4.png)
下面的文档中MyFlutterApplication又改成了androidInit，如下图
![image](https://user-images.githubusercontent.com/23522394/152740909-5c3178f2-ebf8-4f1e-99c0-2d88b4fd10a2.png)

因为有隐私政策的问题，我一开始在onCreate中使用了androidPreInit。那么，请问我应该在哪里写androidInit呢？
期待您的回答，谢谢！

**Comment by zileyuan** [comment]
在安卓代码里面调用 UmengAnalyticsPushFlutterAndroid.androidInit(...)
然后用户接收隐私协议以后，通过flutter 代码调用UmengAnalyticsPush.initUmeng(...);

**Comment by gingerJY** [comment]
> 在安卓代码里面调用 UmengAnalyticsPushFlutterAndroid.androidInit(...) 然后用户接收隐私协议以后，通过flutter 代码调用UmengAnalyticsPush.initUmeng(...);

感谢回复，我去试一下
