### ISSUE TITLE
Android build: AndroidManifest.xml merge error

### ISSUE THREAD

**Issue by timzaak** [zileyuan/umeng_analytics_push#49]
version: 2.1.6, Flutter 3

/Users/timzaak/code/work/android/app/src/main/AndroidManifest.xml:30:13-36 Error:
	Attribute service#com.taobao.accs.ChannelService@exported value=(true) from [:umeng_analytics_push] AndroidManifest.xml:30:13-36
	is also present at [com.umeng.umsdk:push:6.5.2] AndroidManifest.xml:73:13-37 value=(false).
	Suggestion: add 'tools:replace="android:exported"' to <service> element at AndroidManifest.xml:28:9-38:19 to override.
/Users/timzaak/code/work/android/app/src/main/AndroidManifest.xml:41:13-36 Error:
	Attribute service#com.taobao.accs.data.MsgDistributeService@exported value=(true) from [:umeng_analytics_push] AndroidManifest.xml:41:13-36
	is also present at [com.umeng.umsdk:push:6.5.2] AndroidManifest.xml:84:13-37 value=(false).
	Suggestion: add 'tools:replace="android:exported"' to <service> element at AndroidManifest.xml:39:9-45:19 to override.
/Users/timzaak/code/work/android/app/src/main/AndroidManifest.xml:85:13-36 Error:
	Attribute service#org.android.agoo.accs.AgooService@exported value=(true) from [:umeng_analytics_push] AndroidManifest.xml:85:13-36
	is also present at [com.umeng.umsdk:push:6.5.2] AndroidManifest.xml:100:13-37 value=(false).
	Suggestion: add 'tools:replace="android:exported"' to <service> element at AndroidManifest.xml:83:9-89:19 to override.
/Users/timzaak/code/work/android/app/src/main/AndroidManifest.xml:109:13-36 Error:
	Attribute receiver#com.taobao.agoo.AgooCommondReceiver@exported value=(true) from [:umeng_analytics_push] AndroidManifest.xml:109:13-36
	is also present at [com.umeng.umsdk:push:6.5.2] AndroidManifest.xml:127:13-37 value=(false).
	Suggestion: add 'tools:replace="android:exported"' to <receiver> element at AndroidManifest.xml:107:9-119:20 to override.

**Comment by devkou** [comment]
这个问题你这边有解决么？我这也是报这个

**Comment by devkou** [comment]
@zileyuan 大佬 这个是什么情况？

**Comment by timzaak** [comment]
没能解决

**Comment by zileyuan** [comment]
请升级 2.1.8
