### ISSUE TITLE
ios编译错误duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by bigtotorouk** [zileyuan/umeng_analytics_push#5]
/Users/xxx/workspace-flutter/xx_flutter/ios/Pods/UMCAnalytics/UMAnalytics.framework/UMAnalytics(UMComCheckEvent.o)
        /Users/xxx/workspace-flutter/xx_flutter/ios/Pods/UMCCommon/UMCommon.framework/UMCommon(UMComCheckEvent.o)
    ld: 164 duplicate symbols for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by bastYYJ** [comment]
UMAnalytics 和 UMCommon 的包冲突了，很奇怪，我也没有解决。不过我fork一份，去除了ios的UMAnalytics 功能，如果你只要推送的话可以试试用我这个，我还优化了下安卓部分的功能。

**Comment by zileyuan** [comment]
flutter clean 试一试

**Comment by bigtotorouk** [comment]
@zileyuan  试过了还是不行

**Comment by zileyuan** [comment]
你的Xcode是什么版本的，还有就是你之前pod 安装过友盟的组件么？

**Comment by bigtotorouk** [comment]
xcode 是11.5，   pod的chache都clean 了 。 我看ios目录下podfile.lock文件 是这个 ， 你看对吗
![image](https://user-images.githubusercontent.com/1658469/87760770-d67af300-c842-11ea-9839-d896e569d88a.png)

**Comment by bigtotorouk** [comment]
@zileyuan

**Comment by zileyuan** [comment]
> xcode 是11.5， pod的chache都clean 了 。 我看ios目录下podfile.lock文件 是这个 ， 你看对吗
> ![image](https://user-images.githubusercontent.com/1658469/87760770-d67af300-c842-11ea-9839-d896e569d88a.png)

友盟 6.1.0版本的分析是有问题的，我之前这个版本是不能编译，我的版本
  - UMCAnalytics (6.0.5):
    - UMCCommon
  - UMCCommon (2.1.1)
  - UMCCommonLog (1.0.0)
  - UMCPush (3.2.4):
    - UMCCommon
  - umeng_analytics_push (0.0.1):
    - Flutter
    - UMCAnalytics
    - UMCCommon
    - UMCCommonLog
    - UMCPush

**Comment by zileyuan** [comment]
你使用
s.dependency 'UMCCommon','6.0.5'
  s.dependency 'UMCAnalytics','2.1.1'
  s.dependency 'UMCPush','3.2.4'
  s.dependency 'UMCCommonLog','1.0.0'  试试

**Comment by bigtotorouk** [comment]
恩，改完之后好了。多谢 @zileyuan

**Comment by woodymoo** [comment]
@zileyuan  要写到哪个 podspec文件？ UMCCommon.podspec 和 UMCAnalytics.podspec ?
