### ISSUE TITLE
ios 添加点击监听 就会崩溃

### ISSUE THREAD

**Issue by dynamic-bast** [zileyuan/umeng_analytics_push#6]
![截屏2020-07-17 下午4 32 36](https://user-images.githubusercontent.com/38997897/87766642-0ed2ff00-c84c-11ea-8f6f-4fa7b47d6b5b.png)

**Comment by JasonHezz** [comment]
https://github.com/zileyuan/umeng_analytics_push/blob/ce7bb67f856ba0193bdb35b2d86f40555308dffd/ios/Classes/UmengAnalyticsPushPlugin.m#L17

修改成
```
[eventChannel setStreamHandler:instance]; 
```

**Comment by dynamic-bast** [comment]
> https://github.com/zileyuan/umeng_analytics_push/blob/ce7bb67f856ba0193bdb35b2d86f40555308dffd/ios/Classes/UmengAnalyticsPushPlugin.m#L17
> 
> 修改成
> 
> ```
> [eventChannel setStreamHandler:instance]; 
> ```

谢谢，没有报错了，不过ios部分的错误真挺多的。
UNUserNotificationCenter 不能在你的 UmengAnalyticsPushFlutterIos.iosInit 内注册，不会生效的，应该在AppDelegate内注册，还有README.md 内的案例只实现了 一个 userNotificationCenter 方法，这会导致 应用前台时无法发出通知。 只是给点意见哈～
