### ISSUE TITLE
[Enhancement] add notification calllback

### ISSUE THREAD

**Issue by JasonHezz** [zileyuan/umeng_analytics_push#7]
Android:
[增加通知回调](https://developer.umeng.com/docs/67966/detail/98583#h2-u81EAu5B9Au4E49u901Au77E5u680Fu6837u5F0F4)
**每当有通知送达时，均会回调getNotification方法，因此可以通过监听此方法来判断通知是否送达。**

IOS：
completionHandler | iOS10以上的通知认证回调

**Comment by zileyuan** [comment]
看看 1.2 版本可以满足么
